package com.wfm.experts.entity.tenant.common;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.validator.constraints.Length;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

import java.util.Date;

@Getter
@Setter
@Entity
@Table(name = "employees",
        uniqueConstraints = {
                @UniqueConstraint(columnNames = {"email"}),
                @UniqueConstraint(columnNames = {"employeeId"}),
                @UniqueConstraint(columnNames = {"phoneNumber"}) // ✅ Unique Constraint for Phone Number
        })
public class Employee {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @NotBlank(message = "First name is required")
    @Column(nullable = false)
    private String firstName;

    @NotBlank(message = "Last name is required")
    @Column(nullable = false)
    private String lastName;

    @Column(nullable = false)
    private String fullName;  // ✅ Auto-generated by concatenating first and last name

    @NotBlank(message = "Email is required")
    @Email(message = "Invalid email format")
    @Column(nullable = false, unique = true)
    private String email;

    @NotBlank(message = "Phone number is required")
    @Size(max = 20, message = "Phone number must not exceed 20 characters")
    @Column(nullable = false, unique = true, length = 20)  // ✅ Unique Constraint
    private String phoneNumber;

    @NotBlank(message = "Employee ID is required")
    @Length(max = 20, message = "Employee ID must not exceed 20 characters")
    @Column(nullable = false, unique = true, length = 20)
    private String employeeId;  // ✅ Unique Employee ID

    @NotBlank(message = "Password is required")
    @Column(nullable = false)
    private String password;  // ✅ Hashed Password

    @ManyToOne(optional = false, fetch = FetchType.EAGER)  // ✅ One-directional mapping
    @JoinColumn(name = "role_id", nullable = false)
    private Role role;

    @JsonIgnore
    private String tenantId;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(updatable = false)
    private Date createdAt;

    @Temporal(TemporalType.TIMESTAMP)
    private Date updatedAt;

    // ✅ Auto-set timestamps on creation
    @PrePersist
    protected void onCreate() {
        this.createdAt = new Date();
        this.updatedAt = new Date();
        this.fullName = firstName + " " + lastName; // ✅ Generate full name
    }

    // ✅ Auto-update timestamp on modification
    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = new Date();
    }
}
