-- -- V15__create_leave_policy_and_conditional_rule_tables.sql
-- -- Production-grade Flyway migration for Leave Policy & Conditional Rule tables
--
-- -- 1) leave_policy table
-- CREATE TABLE IF NOT EXISTS leave_policy (
--                                             id                          BIGSERIAL PRIMARY KEY,
--                                             leave_name                  VARCHAR(100) NOT NULL,
--     code                        VARCHAR(50) UNIQUE,
--     effective_date              DATE NOT NULL,
--     expiration_date             DATE,
--     profile_select              VARCHAR(20) NOT NULL,
--     calendar_color              VARCHAR(20) NOT NULL,
--     enable_leave_config         BOOLEAN NOT NULL DEFAULT TRUE,
--     measure_by                  leave_measure_by NOT NULL,
--     paid_unpaid                 paid_unpaid NOT NULL,
--     full_day                    BOOLEAN NOT NULL,
--     half_day                    BOOLEAN NOT NULL,
--     max_days_year               INTEGER,
--     max_days_month              INTEGER,
--     max_consecutive_days        INTEGER,
--     min_advance_notice          INTEGER,
--     min_worked                  INTEGER,
--     occurrence_limit            INTEGER,
--     occurrence_period           occurrence_period NOT NULL,
--     enable_carryover_proration  BOOLEAN NOT NULL DEFAULT FALSE,
--     allow_carryover             BOOLEAN NOT NULL DEFAULT FALSE,
--     carryover_cap               INTEGER,
--     calculation_basis           calculation_basis NOT NULL,
--     auto_encash                 BOOLEAN NOT NULL DEFAULT FALSE,
--     allow_proration             BOOLEAN NOT NULL DEFAULT FALSE,
--     proration_mode              proration_mode NOT NULL,
--     join_date_threshold         INTEGER,
--     rounding                    rounding_mode NOT NULL,
--     enable_attachments          BOOLEAN NOT NULL DEFAULT FALSE,
--     attachment_required         BOOLEAN NOT NULL DEFAULT FALSE,
--     pdf                         BOOLEAN NOT NULL DEFAULT FALSE,
--     jpg                         BOOLEAN NOT NULL DEFAULT FALSE,
--     png                         BOOLEAN NOT NULL DEFAULT FALSE,
--     docx                        BOOLEAN NOT NULL DEFAULT FALSE,
--     created_at                  TIMESTAMP WITH TIME ZONE DEFAULT now(),
--     updated_at                  TIMESTAMP WITH TIME ZONE DEFAULT now()
--     );
--
-- -- 2) conditional_rule table
-- CREATE TABLE IF NOT EXISTS conditional_rule (
--                                                 id                          BIGSERIAL PRIMARY KEY,
--                                                 leave_policy_id             BIGINT NOT NULL
--                                                 REFERENCES leave_policy(id)
--     ON DELETE CASCADE,
--     tenure                      INTEGER,
--     override_max                INTEGER,
--     override_min_notice         INTEGER,
--     override_min_worked         INTEGER,
--     override_occurrence_limit   INTEGER,
--     override_occurrence_period  occurrence_period,
--     created_at                  TIMESTAMP WITH TIME ZONE DEFAULT now(),
--     updated_at                  TIMESTAMP WITH TIME ZONE DEFAULT now()
--     );
--
-- -- 3) Triggers to update updated_at automatically
-- CREATE OR REPLACE FUNCTION set_timestamp()
-- RETURNS TRIGGER AS $$
-- BEGIN
--   NEW.updated_at = now();
-- RETURN NEW;
-- END;
-- $$ LANGUAGE plpgsql;
--
-- CREATE TRIGGER trg_leave_policy_updated
--     BEFORE UPDATE ON leave_policy
--     FOR EACH ROW EXECUTE FUNCTION set_timestamp();
--
-- CREATE TRIGGER trg_conditional_rule_updated
--     BEFORE UPDATE ON conditional_rule
--     FOR EACH ROW EXECUTE FUNCTION set_timestamp();
