-- V17__create_roles_and_permissions_tables.sql
-- Creates roles, permissions, and role_permissions join table
-- PostgreSQL-compatible. Uses identity columns and sensible constraints.

-- === ROLES ================================================================
CREATE TABLE IF NOT EXISTS roles (
                                     id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     role_name   VARCHAR(100) NOT NULL UNIQUE
    );

-- Helpful index for lookups by name (unique already creates one, but explicit name is clearer)
CREATE UNIQUE INDEX IF NOT EXISTS ux_roles_role_name ON roles(role_name);

-- === PERMISSIONS ==========================================================
CREATE TABLE IF NOT EXISTS permissions (
                                           id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           name          VARCHAR(100) NOT NULL UNIQUE,      -- e.g., 'employee:create'
    description   VARCHAR(255),                      -- human-readable
    module_name   VARCHAR(100)                       -- e.g., 'HR', 'WFM', 'Payroll'
    );

CREATE UNIQUE INDEX IF NOT EXISTS ux_permissions_name ON permissions(name);
CREATE INDEX IF NOT EXISTS ix_permissions_module_name ON permissions(module_name);

-- === ROLE_PERMISSIONS (JOIN) =============================================
CREATE TABLE IF NOT EXISTS role_permissions (
                                                role_id        BIGINT NOT NULL,
                                                permission_id  BIGINT NOT NULL,
                                                PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_role_permissions_role
    FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
    CONSTRAINT fk_role_permissions_permission
    FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE
    );

-- Optional helper indexes (PK already covers both, but these can speed up one-sided joins)
CREATE INDEX IF NOT EXISTS ix_role_permissions_role_id ON role_permissions(role_id);
CREATE INDEX IF NOT EXISTS ix_role_permissions_permission_id ON role_permissions(permission_id);

-- === (OPTIONAL) SEED EXAMPLES ============================================
-- Uncomment and adjust as needed. Keep seeds in a later migration if you prefer strict separation.
-- INSERT INTO roles (role_name) VALUES
--   ('ADMIN'), ('MANAGER'), ('EMPLOYEE')
-- ON CONFLICT (role_name) DO NOTHING;
--
-- INSERT INTO permissions (name, description, module_name) VALUES
--   ('employee:create', 'Can create employee profiles', 'HR'),
--   ('employee:read',   'Can read employee profiles',   'HR'),
--   ('employee:update', 'Can update employee profiles', 'HR'),
--   ('employee:delete', 'Can delete/terminate profiles','HR')
-- ON CONFLICT (name) DO NOTHING;
--
-- Example mapping (ADMIN gets all):
-- INSERT INTO role_permissions (role_id, permission_id)
-- SELECT r.id, p.id
-- FROM roles r CROSS JOIN permissions p
-- WHERE r.role_name = 'ADMIN'
-- ON CONFLICT DO NOTHING;
