-- V18 Flyway migration script
-- Creates tables for RequestType and its related configurations.

-- 1. Create ValidationConfig Table
CREATE TABLE validation_config
(
    id                   BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    enabled              BOOLEAN NOT NULL,
    sandwich             BOOLEAN NOT NULL,
    holiday_count        BOOLEAN NOT NULL,
    overlap              BOOLEAN NOT NULL,
    probation            BOOLEAN NOT NULL,
    attachment_mandatory BOOLEAN NOT NULL,
    attachment_days      INT     NOT NULL
);

-- 2. Create ClubbingConfig Table
CREATE TABLE clubbing_config
(
    id       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    enabled  BOOLEAN NOT NULL,
    weekends BOOLEAN NOT NULL,
    hols     BOOLEAN NOT NULL,
    max      INT     NOT NULL
);

-- 2.1 Create ElementCollection table for clubbing_with
CREATE TABLE clubbing_with
(
    clubbing_id BIGINT       NOT NULL,
    with_code   VARCHAR(255) NULL,
    CONSTRAINT fk_clubbing_with_on_clubbing_config FOREIGN KEY (clubbing_id) REFERENCES clubbing_config (id)
);

-- 3. Create NotificationConfig Table
CREATE TABLE notification_config
(
    id                BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    enabled           BOOLEAN NOT NULL,
    emp_submit        BOOLEAN NOT NULL,
    emp_approve       BOOLEAN NOT NULL,
    emp_reject        BOOLEAN NOT NULL,
    emp_cancel        BOOLEAN NOT NULL,
    approver_submit   BOOLEAN NOT NULL,
    approver_escalate BOOLEAN NOT NULL,
    approver_cancel   BOOLEAN NOT NULL,
    approver_delete   BOOLEAN NOT NULL,
    listener_submit   BOOLEAN NOT NULL,
    listener_approve  BOOLEAN NOT NULL,
    listener_reject   BOOLEAN NOT NULL,
    listener_cancel   BOOLEAN NOT NULL,
    listener_delete   BOOLEAN NOT NULL
);

-- 3.1 Create ElementCollection table for notification_channels
CREATE TABLE notification_channels
(
    notification_id BIGINT       NOT NULL,
    channel         VARCHAR(255) NULL,
    CONSTRAINT fk_notification_channels_on_notification_config FOREIGN KEY (notification_id) REFERENCES notification_config (id)
);

-- 4. Create ApprovalConfig Table (UPDATED)
CREATE TABLE approval_config
(
    id        BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    enabled   BOOLEAN      NOT NULL,
    mode      VARCHAR(255) NULL,
    escalate  INT          NULL,
    auto_days INT          NULL
);

-- 4.1 Create ElementCollection table for approval_chain_steps
CREATE TABLE approval_chain_steps
(
    approval_id BIGINT       NOT NULL,
    step        VARCHAR(255) NULL,
    CONSTRAINT fk_approval_chain_steps_on_approval_config FOREIGN KEY (approval_id) REFERENCES approval_config (id)
);

-- 4.2 Create ElementCollection table for approval_notify
CREATE TABLE approval_notify
(
    approval_id   BIGINT       NOT NULL,
    notify_target VARCHAR(255) NULL,
    CONSTRAINT fk_approval_notify_on_approval_config FOREIGN KEY (approval_id) REFERENCES approval_config (id)
);

-- 5. Create the main RequestTypes Table
CREATE TABLE request_types
(
    id              BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name            VARCHAR(255) NOT NULL UNIQUE,
    effective_date  DATE         NULL,
    expiration_date DATE         NULL,
    approval_id     BIGINT       NULL,
    clubbing_id     BIGINT       NULL,
    validation_id   BIGINT       NULL,
    notification_id BIGINT       NULL,
    CONSTRAINT fk_request_types_on_approval_config FOREIGN KEY (approval_id) REFERENCES approval_config (id),
    CONSTRAINT fk_request_types_on_clubbing_config FOREIGN KEY (clubbing_id) REFERENCES clubbing_config (id),
    CONSTRAINT fk_request_types_on_validation_config FOREIGN KEY (validation_id) REFERENCES validation_config (id),
    CONSTRAINT fk_request_types_on_notification_config FOREIGN KEY (notification_id) REFERENCES notification_config (id)
);